pipeline {
    agent any

    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                 dir('notification-service') {
                   sh './gradlew assemble'
               }
           }
        }
        stage('Build Docker image') {
            steps {
                dir('notification-service') {
                    script {
                         sh './gradlew docker'
                    }
                } 
            }        
        }
        stage('Push Docker image') {
            environment {
                DOCKER_HUB_LOGIN = credentials('docker-hub')
            }
            steps {
                 dir('notification-service') {
                    script {
                        sh 'docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW'
                        sh './gradlew dockerPush'
                    }
                 }    
            }
        }
    }
}