pipeline {
    agent any

    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
               git branch: 'master', url: 'https://github.com/hugojesusmr/microservicesjenkins.git'
                 dir('config-server') {
                   sh './gradlew assemble'
               }
           }
        }
        stage('Build Docker image') {
            steps {
                git branch: 'master', url: 'https://github.com/hugojesusmr/microservicesjenkins.git'
                  dir('config-server') {
                       sh './gradlew docker'
                  }
            }         
        }
        /* stage('Push Docker image') {
            environment {
                DOCKER_HUB_LOGIN = credentials('docker-hub')
            }
            steps {
                sh 'docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW'
                sh './gradlew dockerPush'
            }
        } */
    }
}