pipeline {
    agent any

    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                 dir('discovery-service') {
                   sh './gradlew assemble'
               }
           }
        }
        stage('Build Docker image') {
            steps {
                dir('discovery-service') {
                    sh './gradlew docker'
                } 
            }        
        }
        stage('Push Docker image') {
            environment {
                DOCKER_HUB_LOGIN = credentials('dockerhub')
            }
            steps {
                 dir('discovery-service') {
                      sh 'docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW'
                      sh './gradlew dockerPush'
                 }    
            }
        }
    }
}