server:
  port: 8761
spring:
  zipkin: 
    base-url: http://localhost:9411
  sleuth:
    sampler:
        probability: 1.0
eureka:
  instance:
     prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/    