server:
  port: 8001 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/order-service
    username: root
    password: password
    
  zipkin: 
    base-url: http://zipkin:9411    
  kafka:
    producer:
        bootstrap-servers: broker:29092     
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka