server:
  port: 8002 
spring:
  data:
    mongodb: 
       host: mongo
       port: 27017
       database: product-service
       
       
       
  zipkin: 
    base-url: http://zipkin:9411    
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka