server:
  port: 8002 
spring:
  data:
    mongodb: 
       host: mongo://localhost:27017/product-service?authSgiource=admin
       username: admin 
       password: secret
       

  zipkin: 
    base-url: http://zipkin:9411    
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka