server:
  port: 8002 
spring:
  data:
    mongodb: 
       host: mongodb-host
       port: 27017
       database: product-service
       authentication-database: admin
       username: root
       password: root
       
       
  zipkin: 
    base-url: http://zipkin:9411    
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka