server:
  port: 8002
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: product-service
  data:
    mongodb: 
        uri: mongodb://admin:admin@localhost:27017/product-service?authSource=admin
  zipkin: 
     base-url: http://localhost:9411
  sleuth:
     sampler:
        probability: 1.0  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
      web:
       exposure:
          include: 
          - prometheus      