server:
  port: 8002
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: product-service
  data:
    mongodb: 
        port: 27027
        database: product-service
  zipkin: 
     base-url: http://localhost:9411
  sleuth:
     sampler:
        probability: 1.0  

eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
      web:
       exposure:
          include: "*"      