server:
  port: 8002 
spring:
  data:
    mongodb: 
       host: mongo
       port: 27017
       database: product-service
       uri: mongo://admin:admin@mongo:27017/product-service?authSource=admin
       username: admin 
       password: secret
       
  zipkin: 
    base-url: http://zipkin:9411    
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka