server:
  port: 8004
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/inventory-service
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
           non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  
    
  zipkin: 
    base-url: http://zipkin:9411    
  
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka