server:
  port: 8004
  error:
    include-message: always
    include-binding-errors: always
spring:
 application:
    name: inventory-service
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/inventory-service
    username: user
    password: password
  
 jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
         ddl-auto: create         
 zipkin: 
   base-url: http://localhost:9411
 sleuth:
   sampler:
     probability: 1.0              
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
         include: "*"
    