server:
  port: 8004
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/inventory-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: password
    
  zipkin: 
    base-url: http://zipkin:9411    
  
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka